//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Falcon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkerpattern {
            get {
                object obj = ResourceManager.GetObject("checkerpattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ftoimg {
            get {
                object obj = ResourceManager.GetObject("ftoimg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loadimage {
            get {
                object obj = ResourceManager.GetObject("loadimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoImage {
            get {
                object obj = ResourceManager.GetObject("NoImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ID&quot;:&quot;1&quot;,&quot;blocknumber&quot;:&quot;7&quot;,&quot;data&quot;:&quot;0000000011111000011000111110001111001010100000000&quot;,&quot;category&quot;:&quot;NyID&quot;},{&quot;ID&quot;:&quot;2&quot;,&quot;blocknumber&quot;:&quot;7&quot;,&quot;data&quot;:&quot;0000000011111000101100111100001111001010100000000&quot;,&quot;category&quot;:&quot;NyID&quot;},{&quot;ID&quot;:&quot;3&quot;,&quot;blocknumber&quot;:&quot;7&quot;,&quot;data&quot;:&quot;0000000011111000001000111100001111001010100000000&quot;,&quot;category&quot;:&quot;NyID&quot;},{&quot;ID&quot;:&quot;4&quot;,&quot;blocknumber&quot;:&quot;7&quot;,&quot;data&quot;:&quot;0000000011111000110100111110001110001010100000000&quot;,&quot;category&quot;:&quot;NyID&quot;},{&quot;ID&quot;:&quot;5&quot;,&quot;blocknumber&quot;:&quot;7&quot;,&quot;data&quot;:&quot;0000000011111000010100111100001110001010100000000&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NyID {
            get {
                return ResourceManager.GetString("NyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap showimage {
            get {
                object obj = ResourceManager.GetObject("showimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
